const fonts = {
  regular: 'Inter_400Regular',
  semiBold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
  extraBold: 'Inter_800ExtraBold',
} as const;


export const feedColors = {
  cardBorder: '#EBE9E2',
  cardSurface: '#FFFFFF',
  tripLine: '#C2410C',
  tripLineInert: '#78716C',
  badgeWell: '#FAF9F5',
  badgeBorder: '#EBE9E2',
  badgeInk: '#78716C',
  tagWell: '#FFF0EC',
  tagInk: '#EA580C',
  caption: '#1C1917',
  captionMore: '#A8A29E',
  authorName: '#1C1917',
  timeSince: '#A8A29E',
  countIdle: '#78716C',
  glyphIdle: '#57534E',
  liked: '#EA580C',
  counterPill: 'rgba(0, 0, 0, 0.5)',
  dotWell: 'rgba(0, 0, 0, 0.4)',
  onPill: '#FFFFFF',
  photoWell: '#E7E5E4',
  skeleton: '#F5F5F4',
  skeletonDash: '#D6D3D1',
  caughtUpWell: '#FFF0EC',
  caughtUpTitle: '#1C1917',
  caughtUpBody: '#78716C',
  pillWell: '#1C1917',
  pillInk: '#FFFFFF',
  headerRule: '#EBE9E2',
  burst: '#FFFFFF',
  sheetScrim: 'rgba(28, 25, 23, 0.4)',
} as const;


export const feedTypography = {
  wordmark: { fontFamily: fonts.extraBold, fontSize: 22, lineHeight: 27, fontWeight: '800' },
  authorName: { fontFamily: fonts.bold, fontSize: 14, lineHeight: 18, fontWeight: '700' },
  timeSince: { fontFamily: fonts.regular, fontSize: 11, lineHeight: 14, fontWeight: '400' },
  tripLine: { fontFamily: fonts.semiBold, fontSize: 11, lineHeight: 14, fontWeight: '600' },
  badge: { fontFamily: fonts.bold, fontSize: 11, lineHeight: 14, fontWeight: '700' },
  tag: { fontFamily: fonts.bold, fontSize: 11, lineHeight: 14, fontWeight: '700' },
  caption: { fontFamily: fonts.regular, fontSize: 14, lineHeight: 19, fontWeight: '400' },
  captionMore: { fontFamily: fonts.semiBold, fontSize: 14, lineHeight: 19, fontWeight: '600' },
  count: { fontFamily: fonts.semiBold, fontSize: 12, lineHeight: 15, fontWeight: '600' },
  counter: { fontFamily: fonts.bold, fontSize: 12, lineHeight: 15, fontWeight: '700' },
  avatarInitials: { fontFamily: fonts.bold, fontSize: 13, lineHeight: 16, fontWeight: '700' },
  caughtUpTitle: { fontFamily: fonts.bold, fontSize: 14, lineHeight: 18, fontWeight: '700' },
  caughtUpBody: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 16, fontWeight: '400' },
  pill: { fontFamily: fonts.bold, fontSize: 12, lineHeight: 15, fontWeight: '700' },
  toast: { fontFamily: fonts.semiBold, fontSize: 13, lineHeight: 17, fontWeight: '600' },
} as const;


export const feedMetrics = {
  cardRadius: 16,
  cardGap: 16,
  listInset: 16,
  cardPadding: 12,
  avatarSize: 36,
  photoHeight: 430,
  headerHeight: 51,
  headerPadding: 20,
  hitTarget: 44,
  iconButton: 36,
  glyph: 20,
  heartGlyph: 18,
  actionGlyph: 17,
  saveGlyph: 16,
  tagGlyph: 12,
  dotSize: 8,
  pillInset: 12,
  burstSize: 96,
  skeletonPhoto: 180,
  caughtUpDisc: 40,
  hideHeaderAfter: 24,
  chipRadius: 6,
  chipPaddingY: 4,
  unreadDot: 8,
  unreadRing: 1.5,
  unreadTop: 7,
  unreadRight: 8,
  skeletonWide: 120,
  skeletonNarrow: 80,
  skeletonBarTall: 10,
  skeletonBarShort: 8,
} as const;
