import { dm, figtree, geist, inter, outfit } from './memoryFonts';


export const memoryColors = {
  screen: '#FFFFFF',
  paper: '#FAF9F5',
  card: '#FFFFFF',
  hairline: '#E7E5E4',
  divider: '#EFEBE4',
  dashed: '#E2E4E8',
  wellDivider: '#F5F5F4',
  hover: '#FAFAF9',
  title: '#1C1917',
  label: '#1B263B',
  bio: '#44403C',
  body: '#57534E',
  muted: '#78716C',
  faint: '#A19B95',
  disabledDate: '#D6D3D1',
  chevronIdle: '#A8A29E',
  accent: '#EA580C',
  accentDeep: '#C2410C',
  accentWash: '#FDE4CF',
  rangeBand: '#FFF0E6',
  highlightWash: '#FFF7ED',
  cta: '#F05A28',
  ctaDisabled: '#F5C4AE',
  check: '#FF5A3C',
  diaryPillInk: '#5B3BFF',
  diaryPillWell: '#F0EBFF',
  postcardPillInk: '#5B3BFF',
  postcardPillWell: '#F0EBFF',
  successWell: '#D1FAE5',
  successInk: '#054D38',
  danger: '#B91C1C',
  darkToastWell: '#1C1917',
  darkToastInk: '#FFFFFF',
  diaryRowWell: '#FAF9F5',
  diaryRowBorder: '#EBE9E2',
  cancelWell: '#FAF9F5',
  scrim: 'rgba(28, 25, 23, 0.45)',
  confirmScrim: 'rgba(28, 25, 23, 0.55)',
  overlayButton: 'rgba(28, 25, 23, 0.45)',
  changePill: 'rgba(28, 25, 23, 0.6)',
  photoPill: 'rgba(0, 0, 0, 0.5)',
  coverGradientTop: 'rgba(28, 25, 23, 0)',
  coverGradientBottom: 'rgba(28, 25, 23, 0.7)',
  onCover: '#FFFFFF',
  onCoverMuted: 'rgba(255, 255, 255, 0.85)',
  white: '#FFFFFF',
} as const;


export const memoryMetrics = {
  frameWidth: 393,
  screenPadding: 20,
  ctaSideMargin: 16,
  headerButton: 36,
  headerChevron: 22,
  headerButtonPull: -8,
  pillPaddingV: 4,
  pillPaddingH: 8,
  pillRadius: 6,
  fieldHeight: 48,
  fieldRadius: 10,
  fieldPaddingH: 14,
  placeFieldHeight: 44,
  captionMin: 72,
  postcardCaptionMin: 96,
  coverHeight: 120,
  coverRadius: 12,
  dashedWidth: 1.5,
  cardRadius: 12,
  cardPadding: 14,
  cardGap: 12,
  tileColumns: 3,
  tileGap: 8,
  tileRadius: 12,
  checkSize: 22,
  checkBorder: 2,
  photosPerPostcard: 5,
  stripPhoto: 200,
  ctaHeight: 50,
  ctaRadius: 4,
  sheetRadius: 20,
  sheetPaddingTop: 10,
  sheetPaddingH: 20,
  sheetMaxShare: 0.7,
  grabberWidth: 36,
  grabberHeight: 4,
  sheetRowPaddingV: 14,
  sheetIconTile: 44,
  sheetIconTileRadius: 12,
  sheetRowIcon: 20,
  cancelHeight: 48,
  cancelRadius: 10,
  chipHeight: 48,
  chipRadius: 10,
  chipActiveBorder: 1.5,
  calendarCell: 40,
  calendarRowGap: 6,
  calendarChevron: 20,
  avatar: 72,
  avatarSmall: 28,
  statsRadius: 14,
  statsPaddingV: 10,
  tabBar: 3,
  loosePhoto: 220,
  looseRadius: 12,
  looseBodyPaddingV: 12,
  looseBodyPaddingH: 14,
  kebab: 18,
  sectionPadding: 12,
  sectionThumb: 44,
  sectionThumbRadius: 8,
  chevronHit: 32,
  sectionPostcardPhoto: 180,
  sectionPostcardRadius: 8,
  toastTop: 52,
  toastSide: 16,
  toastRadius: 10,
  toastPaddingV: 12,
  toastPaddingH: 14,
  emptyIcon: 48,
  emptySidePadding: 40,
  detailCover: 260,
  overlayButton: 36,
  overlayButtonTop: 48,
  overlayButtonSide: 12,
  dayPhoto: 200,
  dayPhotoRadius: 12,
  addDayHeight: 44,
  addDayRadius: 10,
  detailPhoto: 393,
  dot: 6,
  detailBodyPaddingV: 14,
  detailBodyPaddingH: 16,
  diaryRowRadius: 10,
  diaryRowPaddingV: 10,
  diaryRowPaddingH: 12,
  filingRowPaddingV: 12,
  confirmWidth: 300,
  confirmRadius: 16,
  confirmPaddingTop: 20,
  confirmPaddingH: 20,
  confirmPaddingBottom: 16,
  confirmButton: 44,
  confirmButtonRadius: 4,
  confirmButtonGap: 10,
  navIcon: 22,
  navStroke: 1.8,
  iconStroke: 1.8,
} as const;


export const memoryMotion = {
  scrimMs: 200,
  sheetInMs: 260,
  sheetOutMs: 200,
  sheetBezier: [0.2, 0.8, 0.2, 1] as const,
  toastInMs: 220,
  toastHoldMs: 2000,
  toastOutMs: 180,
  toastTravel: -12,
  toastOutTravel: -8,
  confirmScrimMs: 180,
  confirmInMs: 180,
  confirmOutMs: 140,
  rowExitMs: 220,
  rowExitTravel: 6,
  rowEnterMs: 200,
  rowEnterScale: 0.92,
  cardFadeInMs: 200,
  washMs: 1000,
  checkPopMs: 220,
  checkPopBezier: [0.2, 0.9, 0.3, 1.3] as const,
  dotFillMs: 120,
  bandFadeMs: 160,
  chipSwapMs: 160,
  pressOpacity: 0.6,
  ctaPressScale: 0.98,
  roundPressScale: 0.92,
  tilePressScale: 0.96,
  pressMs: 120,
  chevronTurnMs: 200,
} as const;


export const memoryTypography = {
  screenTitle: { fontFamily: outfit, fontSize: 22, lineHeight: 28 },
  confirmTitle: { fontFamily: outfit, fontSize: 18, lineHeight: 24 },
  dayTitle: { fontFamily: outfit, fontSize: 16, lineHeight: 21 },
  dayRowTitle: { fontFamily: outfit, fontSize: 15, lineHeight: 20 },

  fieldLabel: { fontFamily: dm.semiBold, fontSize: 14, lineHeight: 18 },
  input: { fontFamily: dm.regular, fontSize: 15, lineHeight: 20 },
  sheetRow: { fontFamily: dm.semiBold, fontSize: 16, lineHeight: 21 },
  cta: { fontFamily: dm.semiBold, fontSize: 16, lineHeight: 20 },
  confirmButton: { fontFamily: dm.semiBold, fontSize: 15, lineHeight: 20 },
  outlinedButton: { fontFamily: dm.semiBold, fontSize: 14, lineHeight: 18 },
  addTile: { fontFamily: dm.medium, fontSize: 12, lineHeight: 15 },
  monthName: { fontFamily: dm.semiBold, fontSize: 16, lineHeight: 20 },
  calendarCell: { fontFamily: dm.regular, fontSize: 15, lineHeight: 18 },
  calendarEdge: { fontFamily: dm.semiBold, fontSize: 15, lineHeight: 18 },

  subtitle: { fontFamily: geist.regular, fontSize: 13, lineHeight: 18 },
  meta13: { fontFamily: geist.regular, fontSize: 13, lineHeight: 18 },
  confirmBody: { fontFamily: geist.regular, fontSize: 13, lineHeight: 19.5 },
  pill: { fontFamily: geist.bold, fontSize: 11, lineHeight: 14, letterSpacing: 0.6 },
  chipCaption: { fontFamily: geist.semiBold, fontSize: 11, lineHeight: 14 },
  weekday: { fontFamily: geist.semiBold, fontSize: 11, lineHeight: 14 },
  counter: { fontFamily: geist.regular, fontSize: 12, lineHeight: 15 },
  tabActive: { fontFamily: geist.bold, fontSize: 14, lineHeight: 18 },
  tabIdle: { fontFamily: geist.medium, fontSize: 14, lineHeight: 18 },

  cardTitle: { fontFamily: figtree.bold, fontSize: 15, lineHeight: 20 },
  caption: { fontFamily: figtree.regular, fontSize: 14, lineHeight: 20 },
  captionLarge: { fontFamily: figtree.regular, fontSize: 15, lineHeight: 21.75 },
  cardMeta: { fontFamily: figtree.regular, fontSize: 12, lineHeight: 16 },
  cardMetaStrong: { fontFamily: figtree.semiBold, fontSize: 12, lineHeight: 16 },
  contextLabel: { fontFamily: figtree.semiBold, fontSize: 12, lineHeight: 16 },
  photoPill: { fontFamily: figtree.bold, fontSize: 11, lineHeight: 14 },
  eyebrow: { fontFamily: figtree.bold, fontSize: 11, lineHeight: 14, letterSpacing: 1 },
  toast: { fontFamily: figtree.semiBold, fontSize: 14, lineHeight: 18 },
  authorName: { fontFamily: figtree.bold, fontSize: 13, lineHeight: 17 },
  authorMeta: { fontFamily: figtree.regular, fontSize: 13, lineHeight: 17 },
  placeRow: { fontFamily: figtree.regular, fontSize: 13, lineHeight: 17 },
  bold16: { fontFamily: figtree.bold, fontSize: 16, lineHeight: 21 },

  displayName: { fontFamily: inter.extraBold, fontSize: 22, lineHeight: 27 },
  handle: { fontFamily: inter.regular, fontSize: 13, lineHeight: 17 },
  bio: { fontFamily: inter.regular, fontSize: 13.5, lineHeight: 18 },
  statValue: { fontFamily: inter.bold, fontSize: 16, lineHeight: 20 },
  statLabel: { fontFamily: inter.regular, fontSize: 11, lineHeight: 14 },
  nav: { fontFamily: inter.medium, fontSize: 11, lineHeight: 14 },
} as const;
