export interface Country {
  readonly code: string;
  readonly name: string;
  readonly currency: string;
}


const HOME_MARKET_FIRST: Country = { code: 'PH', name: 'Philippines', currency: 'PHP' };


const ELSEWHERE: readonly Country[] = [
  { code: 'AD', name: 'Andorra', currency: 'EUR' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED' },
  { code: 'AF', name: 'Afghanistan', currency: 'AFN' },
  { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD' },
  { code: 'AL', name: 'Albania', currency: 'ALL' },
  { code: 'AM', name: 'Armenia', currency: 'AMD' },
  { code: 'AO', name: 'Angola', currency: 'AOA' },
  { code: 'AW', name: 'Aruba', currency: 'AWG' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM' },
  { code: 'BB', name: 'Barbados', currency: 'BBD' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF' },
  { code: 'BI', name: 'Burundi', currency: 'BIF' },
  { code: 'BJ', name: 'Benin', currency: 'XOF' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN' },
  { code: 'BW', name: 'Botswana', currency: 'BWP' },
  { code: 'BY', name: 'Belarus', currency: 'BYN' },
  { code: 'BZ', name: 'Belize', currency: 'BZD' },
  { code: 'CD', name: 'Congo (Kinshasa)', currency: 'CDF' },
  { code: 'CG', name: 'Congo (Brazzaville)', currency: 'XAF' },
  { code: 'CI', name: "Cote d'Ivoire", currency: 'XOF' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC' },
  { code: 'CU', name: 'Cuba', currency: 'CUP' },
  { code: 'CV', name: 'Cabo Verde', currency: 'CVE' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD' },
  { code: 'EC', name: 'Ecuador', currency: 'USD' },
  { code: 'EE', name: 'Estonia', currency: 'EUR' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD' },
  { code: 'GE', name: 'Georgia', currency: 'GEL' },
  { code: 'GH', name: 'Ghana', currency: 'GHS' },
  { code: 'GM', name: 'Gambia', currency: 'GMD' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ' },
  { code: 'GU', name: 'Guam', currency: 'USD' },
  { code: 'GY', name: 'Guyana', currency: 'GYD' },
  { code: 'HN', name: 'Honduras', currency: 'HNL' },
  { code: 'HT', name: 'Haiti', currency: 'HTG' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD' },
  { code: 'IR', name: 'Iran', currency: 'IRR' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD' },
  { code: 'JO', name: 'Jordan', currency: 'JOD' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR' },
  { code: 'LV', name: 'Latvia', currency: 'EUR' },
  { code: 'LY', name: 'Libya', currency: 'LYD' },
  { code: 'MD', name: 'Moldova', currency: 'MDL' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA' },
  { code: 'MK', name: 'North Macedonia', currency: 'MKD' },
  { code: 'ML', name: 'Mali', currency: 'XOF' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT' },
  { code: 'MT', name: 'Malta', currency: 'EUR' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR' },
  { code: 'MW', name: 'Malawi', currency: 'MWK' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN' },
  { code: 'NA', name: 'Namibia', currency: 'NAD' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO' },
  { code: 'NC', name: 'New Caledonia', currency: 'XPF' },
  { code: 'OM', name: 'Oman', currency: 'OMR' },
  { code: 'PA', name: 'Panama', currency: 'PAB' },
  { code: 'PF', name: 'French Polynesia', currency: 'XPF' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK' },
  { code: 'PR', name: 'Puerto Rico', currency: 'USD' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG' },
  { code: 'RS', name: 'Serbia', currency: 'RSD' },
  { code: 'RU', name: 'Russia', currency: 'RUB' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR' },
  { code: 'SN', name: 'Senegal', currency: 'XOF' },
  { code: 'SR', name: 'Suriname', currency: 'SRD' },
  { code: 'SV', name: 'El Salvador', currency: 'USD' },
  { code: 'TN', name: 'Tunisia', currency: 'TND' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD' },
  { code: 'UG', name: 'Uganda', currency: 'UGX' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS' },
  { code: 'VE', name: 'Venezuela', currency: 'VES' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV' },
  { code: 'WS', name: 'Samoa', currency: 'WST' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWG' },
  { code: 'AR', name: 'Argentina', currency: 'ARS' },
  { code: 'AT', name: 'Austria', currency: 'EUR' },
  { code: 'AU', name: 'Australia', currency: 'AUD' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT' },
  { code: 'BE', name: 'Belgium', currency: 'EUR' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD' },
  { code: 'BN', name: 'Brunei', currency: 'BND' },
  { code: 'BR', name: 'Brazil', currency: 'BRL' },
  { code: 'CA', name: 'Canada', currency: 'CAD' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF' },
  { code: 'CL', name: 'Chile', currency: 'CLP' },
  { code: 'CN', name: 'China', currency: 'CNY' },
  { code: 'CO', name: 'Colombia', currency: 'COP' },
  { code: 'CZ', name: 'Czechia', currency: 'CZK' },
  { code: 'DE', name: 'Germany', currency: 'EUR' },
  { code: 'DK', name: 'Denmark', currency: 'DKK' },
  { code: 'EG', name: 'Egypt', currency: 'EGP' },
  { code: 'ES', name: 'Spain', currency: 'EUR' },
  { code: 'FI', name: 'Finland', currency: 'EUR' },
  { code: 'FR', name: 'France', currency: 'EUR' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP' },
  { code: 'GR', name: 'Greece', currency: 'EUR' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD' },
  { code: 'HR', name: 'Croatia', currency: 'EUR' },
  { code: 'HU', name: 'Hungary', currency: 'HUF' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR' },
  { code: 'IE', name: 'Ireland', currency: 'EUR' },
  { code: 'IL', name: 'Israel', currency: 'ILS' },
  { code: 'IN', name: 'India', currency: 'INR' },
  { code: 'IS', name: 'Iceland', currency: 'ISK' },
  { code: 'IT', name: 'Italy', currency: 'EUR' },
  { code: 'JP', name: 'Japan', currency: 'JPY' },
  { code: 'KE', name: 'Kenya', currency: 'KES' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR' },
  { code: 'KR', name: 'South Korea', currency: 'KRW' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD' },
  { code: 'LA', name: 'Laos', currency: 'LAK' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR' },
  { code: 'MA', name: 'Morocco', currency: 'MAD' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK' },
  { code: 'MO', name: 'Macao', currency: 'MOP' },
  { code: 'MV', name: 'Maldives', currency: 'MVR' },
  { code: 'MX', name: 'Mexico', currency: 'MXN' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR' },
  { code: 'NO', name: 'Norway', currency: 'NOK' },
  { code: 'NP', name: 'Nepal', currency: 'NPR' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD' },
  { code: 'PE', name: 'Peru', currency: 'PEN' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR' },
  { code: 'PL', name: 'Poland', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', currency: 'EUR' },
  { code: 'QA', name: 'Qatar', currency: 'QAR' },
  { code: 'RO', name: 'Romania', currency: 'RON' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR' },
  { code: 'SE', name: 'Sweden', currency: 'SEK' },
  { code: 'SG', name: 'Singapore', currency: 'SGD' },
  { code: 'TH', name: 'Thailand', currency: 'THB' },
  { code: 'TR', name: 'Turkiye', currency: 'TRY' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH' },
  { code: 'US', name: 'United States', currency: 'USD' },
  { code: 'VN', name: 'Vietnam', currency: 'VND' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR' },
];


export const COUNTRIES: readonly Country[] = [
  HOME_MARKET_FIRST,
  ...[...ELSEWHERE].sort((left, right) => left.name.localeCompare(right.name)),
];


export const CURRENCIES: readonly string[] = [
  ...new Set(COUNTRIES.map((country) => country.currency)),
].sort();


const CURRENCY_SYMBOLS: Readonly<Record<string, string>> = {
  PHP: '₱',
  USD: '$',
  EUR: '€',
  GBP: '£',
  JPY: '¥',
  CNY: '¥',
  KRW: '₩',
  INR: '₹',
  THB: '฿',
  VND: '₫',
  IDR: 'Rp',
  MYR: 'RM',
  SGD: 'S$',
  AUD: 'A$',
  NZD: 'NZ$',
  CAD: 'C$',
  HKD: 'HK$',
  TWD: 'NT$',
  BRL: 'R$',
  MXN: 'Mex$',
  ZAR: 'R',
  TRY: '₺',
  RUB: '₽',
  ILS: '₪',
  NGN: '₦',
  UAH: '₴',
  KHR: '៛',
  LAK: '₭',
  MNT: '₮',
  BDT: '৳',
  LKR: 'Rs',
  NPR: 'Rs',
  PKR: 'Rs',
  CHF: 'CHF',
};


export function currencyLabel(code: string): string {
  const symbol = CURRENCY_SYMBOLS[code];
  return symbol === undefined ? code : `${code} (${symbol})`;
}


export function countryByCode(code: string | null | undefined): Country | undefined {
  if (code === null || code === undefined) return undefined;
  const normalized = code.trim().toUpperCase();
  return COUNTRIES.find((country) => country.code === normalized);
}
