-- V52 — the old entries table loses its two plan-world chains (CM-1 ticket 07, ADR-035).
--
-- Both drops were signed under the stop rules at CM-1's grilling, and both exist for the same
-- reason: real trip destruction ships in this story, and nothing destroyed may cascade into
-- content that is meant to survive.
--
-- The itinerary cascade (V27's "the only cascade that should reach this table") was written when
-- deleting a trip did not exist. Now it does — and the cutover backfill (rewire story) still needs
-- every old-world entry as its source material, while the survival rule says a member's posted
-- content outlives the owner's destruction. A cascade here would silently vaporize both.
--
-- The activity SET NULL goes with it: the new world's postcards keep a DANGLING provenance pointer
-- when a plan activity dies (V51's design), and the old table now behaves the same way — the
-- entry's snapshot is what travelers read, the activity id is only the trail back. Reads already
-- tolerate an id that resolves to nothing; after the cutover backfill the pointer's fate belongs
-- to the postcard table anyway.
--
-- The constraint names are Postgres's defaults for V27's inline REFERENCES; the stepping IT proves
-- both drops landed and that the two behaviors actually changed (survival on trip delete, dangling
-- id on activity delete), so a renamed constraint cannot silently no-op this migration.
ALTER TABLE diary_entry DROP CONSTRAINT diary_entry_itinerary_id_fkey;
ALTER TABLE diary_entry DROP CONSTRAINT diary_entry_activity_id_fkey;
