export const SCREEN_LABELS: Readonly<Record<string, string>> = {
  '(tabs)/(home)': 'Home feed',
  '(tabs)/(home)/feed/diary/[id]': 'Diary post',
  '(tabs)/(home)/feed/published/[id]': 'Published trip',

  '(tabs)/(discover)/discover': 'Discover',
  '(tabs)/(discover)/discovery-search': 'Discover search',
  '(tabs)/(discover)/discovery-results': 'Discover results',
  '(tabs)/(discover)/discovery-people': 'Discover people',

  '(tabs)/(trips)/trips': 'Trips',
  '(tabs)/(trips)/create': 'Create trip',
  '(tabs)/(trips)/itineraries/new': 'New trip',
  '(tabs)/(trips)/itineraries/archived': 'Archived trips',
  '(tabs)/(trips)/itineraries/[id]': 'Trip overview',
  '(tabs)/(trips)/itineraries/[id]/activity': 'Activity',
  '(tabs)/(trips)/itineraries/[id]/created': 'Trip created',
  '(tabs)/(trips)/itineraries/[id]/days': 'Trip days',
  '(tabs)/(trips)/itineraries/[id]/days/[dayId]': 'Trip day',
  '(tabs)/(trips)/itineraries/[id]/diary': 'Trip diary',
  '(tabs)/(trips)/itineraries/[id]/diary/[entryId]': 'Trip diary entry',
  '(tabs)/(trips)/itineraries/[id]/diary/compose': 'Compose diary entry',
  '(tabs)/(trips)/itineraries/[id]/diary/posted': 'Diary entry posted',
  '(tabs)/(trips)/itineraries/[id]/edit': 'Edit trip',
  '(tabs)/(trips)/itineraries/[id]/edit-plan': 'Edit plan',
  '(tabs)/(trips)/itineraries/[id]/forked': 'Trip forked',
  '(tabs)/(trips)/itineraries/[id]/polls/new': 'New poll',
  '(tabs)/(trips)/itineraries/[id]/preview': 'Trip preview',
  '(tabs)/(trips)/itineraries/[id]/published': 'Trip published',
  '(tabs)/(trips)/published/[id]': 'Published trip',

  '(tabs)/(profile)/profile': 'Profile',
  '(tabs)/(profile)/account': 'Account',
  '(tabs)/(profile)/diary/[id]': 'My diary',
  '(tabs)/(profile)/diary/[id]/[entryId]': 'My diary entry',
  '(tabs)/(profile)/showcase/[id]': 'Showcase',

  'travelers/[handle]': 'Traveler profile',
  'travelers/[handle]/followers': 'Followers',
  'travelers/[handle]/following': 'Following',

  'onboarding/goals': 'Onboarding goals',
  'onboarding/interests': 'Onboarding interests',
  'onboarding/profile': 'Onboarding profile',
  'onboarding/travel-setup': 'Onboarding travel setup',
  'onboarding/complete': 'Onboarding complete',

  'welcome': 'Welcome',
  'sign-in': 'Sign in',
  'sign-up': 'Sign up',
  'verify-code': 'Verify code',
  'join/[token]': 'Invite',
  'health': 'Health',
  'map': 'Map',
  '': 'Home feed',
};
